{{
    config(
        materialized='table'
    )
}}

with sources as(

select distinct ID,STATUS,BILLING_STREET,BILLING_CITY,BILLING_STATE,BILLING_POSTAL_CODE,BILLING_COUNTRY,
SHIPPING_STREET,SHIPPING_CITY,SHIPPING_STATE,SHIPPING_POSTAL_CODE,SHIPPING_COUNTRY,
current_timestamp() as order_load_time from "DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."ORDER")

select ID,STATUS,BILLING_STREET,BILLING_CITY,BILLING_STATE,BILLING_POSTAL_CODE,BILLING_COUNTRY,
SHIPPING_STREET,SHIPPING_CITY,SHIPPING_STATE,SHIPPING_POSTAL_CODE,SHIPPING_COUNTRY,order_load_time
from sources