{{
    config(
        materialized='table'
    )
}}

select O.ID as order_Id,A.ID,C.ID as campain_ID,case_s.ID as case_id,Contact.ID as contact_Id,Contract.ID as Contract_id,
L.ID as LEAD_ID,opp.ID as opp_ID,P.ID as product_id,
A.NAME as A_name,A.TYPE,A.BILLING_STREET,A.BILLING_CITY,A.BILLING_STATE,A.BILLING_POSTAL_CODE,
A.BILLING_COUNTRY,A.SHIPPING_STREET,A.SHIPPING_CITY,A.SHIPPING_STATE,A.SHIPPING_POSTAL_CODE,A.SHIPPING_COUNTRY,
A.INDUSTRY,A.OWNERSHIP,A.RATING,A.UPSELL_OPPORTUNITY_C,A.CUSTOMER_PRIORITY_C,A.ACTIVE_C,C.NAME as C_name,C.TYPE as C_type,
C.STATUS,C.EXPECTED_REVENUE,C.BUDGETED_COST,C.ACTUAL_COST,case_s.SUPPLIED_NAME,case_s.SUPPLIED_COMPANY,case_s.TYPE as case_s_TYPE,
case_s.STATUS as case_s_STATUS,case_s.REASON,case_s.PRIORITY,case_s.POTENTIAL_LIABILITY_C,Contact.NAME as Contact_NAME,
Contact.MAILING_STREET,Contact.MAILING_CITY,Contact.MAILING_STATE,Contact.MAILING_POSTAL_CODE,Contact.MAILING_COUNTRY,
Contact.PHONE,Contact.MOBILE_PHONE,Contact.EMAIL,Contract.BILLING_STREET as Contract_BILLING_STREET,
Contract.BILLING_CITY as Contract_BILLING_CITY,Contract.BILLING_STATE as Contract_BILLING_STATE,
Contract.BILLING_POSTAL_CODE as Contract_BILLING_POSTAL_CODE,Contract.BILLING_COUNTRY as Contract_BILLING_COUNTRY,
Contract.STATUS as Contract_STATUS,Contract.COMPANY_SIGNED_ID,Contract.CUSTOMER_SIGNED_ID,
Contract.CUSTOMER_SIGNED_TITLE,Contract.CUSTOMER_SIGNED_DATE,L.LAST_NAME,L.FIRST_NAME,L.NAME as L_name,L.COMPANY,L.STREET,L.CITY,L.STATE,
L.POSTAL_CODE,L.COUNTRY,L.STATUS as L_STATUS,opp.NAME as opp_NAME,opp.STAGE_NAME,opp.TYPE as opp_TYPE,opp.LEAD_SOURCE,
opp.FORECAST_CATEGORY,opp.MAIN_COMPETITORS_C,opp.AMOUNT,p.NAME as p_NAME,p.PRODUCT_CODE,p.IS_ACTIVE,O.STATUS as O_STATUS,
O.BILLING_STREET as O_BILLING_STREET,O.BILLING_CITY as O_BILLING_CITY,O.BILLING_STATE as O_BILLING_STATE,
O.BILLING_POSTAL_CODE as O_BILLING_POSTAL_CODE,O.BILLING_COUNTRY as O_BILLING_COUNTRY,O.SHIPPING_STREET as O_SHIPPING_STREET,
O.SHIPPING_CITY as O_SHIPPING_CITY,O.SHIPPING_STATE as O_SHIPPING_STATE,O.SHIPPING_POSTAL_CODE as O_SHIPPING_POSTAL_CODE,
O.SHIPPING_COUNTRY as O_SHIPPING_COUNTRY from "DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."ACCOUNT" as A
left join"DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."OPPORTUNITY" as opp on A.ID=opp.ACCOUNT_ID
left join "DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."CAMPAIGN" as C on C.ID=opp.CAMPAIGN_ID and A.ID=opp.ACCOUNT_ID
left join "DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."CASE" as case_s on A.ID=case_s.ACCOUNT_ID
left join  "DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."CONTACT" as Contact on A.ID=contact.ACCOUNT_ID
left join "DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."CONTRACT" as Contract on A.ID=Contract.ACCOUNT_ID
left join "DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."LEAD" as L on A.ID=L.CONVERTED_ACCOUNT_ID
left join "DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."ORDER" as O on A.ID=O.ACCOUNT_ID
left join "DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."ORDER_ITEM" as o_i on o_i.ORDER_ID=O.ID and A.ID=O.ACCOUNT_ID
left join  "DEVELOPER_DB"."TIRUPATHIRAO_SCHEMA"."PRODUCT_2" as p on p.ID=o_i.PRODUCT_2_ID and o_i.ORDER_ID=O.ID and A.ID=O.ACCOUNT_ID
